### ISSUE TITLE
Server timeout when loading exons

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/chanjo2#290]
Hi again, back with another issue, probably something related to our setup. Pointers would be appreciated.

Previously I have been able to load the genes, transcripts and exons into the MariaDB.

When now running it on the production server I get a string of errors specifically when loading exons. Transcripts also initially gave issues, but this was resolved by increasing the timeout time (it took ~5 minutes).

Not sure exactly what happens, but looks like it times out after 7-10 minutes when running:

```
$ time curl -X 'POST' 'http://cmdscout2.lund.skane.se/chanjo2/intervals/load/exons/GRCh38' -H 'accept: application/json' -d ''
```

My instinct is that this is due to some server limitations being hit, so I increased the timeout threshold to 1200 in the `unicorn.conf.py`.

First part of the Chanjo2 unicorn configuration as printed by the logs:

```
ESC[36mchanjo2               |ESC[0m [2024-04-19 08:10:36 +0000] [1] [DEBUG] Current configuration:
ESC[36mchanjo2               |ESC[0m   config: gunicorn.conf.py
ESC[36mchanjo2               |ESC[0m   wsgi_app: None
ESC[36mchanjo2               |ESC[0m   bind: ['0.0.0.0:8000']
ESC[36mchanjo2               |ESC[0m   backlog: 2048
ESC[36mchanjo2               |ESC[0m   workers: 2
ESC[36mchanjo2               |ESC[0m   worker_class: uvicorn.workers.UvicornWorker
ESC[36mchanjo2               |ESC[0m   threads: 4
ESC[36mchanjo2               |ESC[0m   worker_connections: 1000
ESC[36mchanjo2               |ESC[0m   max_requests: 0
ESC[36mchanjo2               |ESC[0m   max_requests_jitter: 0
ESC[36mchanjo2               |ESC[0m   timeout: 1200
ESC[36mchanjo2               |ESC[0m   graceful_timeout: 30
ESC[36mchanjo2               |ESC[0m   keepalive: 2
```

I get a long string of errors which all seems related and probably due to some timeout:

```
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/urllib3/response.py", line 710, in _error_catcher
    yield
  File "/venv/lib/python3.11/site-packages/urllib3/response.py", line 1073, in read_chunked
    self._update_chunk_length()
  File "/venv/lib/python3.11/site-packages/urllib3/response.py", line 1008, in _update_chunk_length
    raise InvalidChunkLength(self, line) from None
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/venv/lib/python3.11/site-packages/urllib3/response.py", line 933, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/venv/lib/python3.11/site-packages/urllib3/response.py", line 1061, in read_chunked
    with self._error_catcher():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/venv/lib/python3.11/site-packages/urllib3/response.py", line 727, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/worker/app/src/chanjo2/endpoints/intervals.py", line 161, in load_exons
    nr_loaded_exons: int = await update_exons(build=build, session=session)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/src/chanjo2/meta/handle_load_intervals.py", line 200, in update_exons
    for line in lines:
  File "/venv/lib/python3.11/site-packages/requests/models.py", line 865, in iter_lines
    for chunk in self.iter_content(
  File "/venv/lib/python3.11/site-packages/requests/utils.py", line 571, in stream_decode_response_unicode
    for chunk in iterator:
  File "/venv/lib/python3.11/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/app/src/chanjo2/endpoints/intervals.py", line 167, in load_exons
    raise HTTPException(
fastapi.exceptions.HTTPException
```

Any ideas here? This has worked on other computers (less heavily loaded than our Scout server). Also the genes and transcripts loading succeeded, just exons failing.

Will have to ease the load on the Scout server now for our geneticists to be able to work, but will continue looking into this next week ..

**Comment by northwestwitch** [comment]
Weird, it shouldn't take all this time. I think on our server it loads exons in about 1 minute or so (haven't tried today tho). Could be that the Ensembl Biomart has issues (wouldn't be the first time. Let's see next week. Have a nice weekend! :)

**Comment by northwestwitch** [comment]
Tried now and took some minutes, but eventually worked on our server:

<img width="621" alt="image" src="https://github.com/Clinical-Genomics/chanjo2/assets/28093618/eab2a0a2-6ff2-413e-9c2b-f09fd600ea2a">

**Comment by Jakob37** [comment]
> Tried now and took some minutes, but eventually worked on our server:
> <img alt="image" width="621" src="https://private-user-images.githubusercontent.com/28093618/324339998-eab2a0a2-6ff2-413e-9c2b-f09fd600ea2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjY0MzEsIm5iZiI6MTcxMzc2NjEzMSwicGF0aCI6Ii8yODA5MzYxOC8zMjQzMzk5OTgtZWFiMmEwYTItNmZmMi00MTNlLTljMmItZjA5ZmQ2MDBlYTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA2MDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNTg1ZjE2OTIxYmExOWQ1NWI2YmU2MjE2NzNjNTA2MzM5ZTNkZTA0NmZmNDQxOGE5NWJmMmU1MGFlODJjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P_qSskCnj78R1-RMaifHK1by03sNhCpZHsh4ZoMQtP0">

OK I see, thank you for testing! I suspect we have much slower hardware than you guys. Could it be that it hits some max connection time for BioMart (~10 minutes) due to slow write speed and times out?

I'll try again when our Scout environment isn't in active use (I brought down Scout for everyone last week when testing this ..)

**Comment by northwestwitch** [comment]
> Could it be that it hits some max connection time for BioMart (~10 minutes) due to slow write speed and times out?

Could be

Alternatively you could download the exons using [schug](https://github.com/Clinical-Genomics/schug) on your local computer and then use the downloaded file as file path to do the loading on chanjo2:

<img width="969" alt="image" src="https://github.com/Clinical-Genomics/chanjo2/assets/28093618/3283d5d8-a26c-400a-bb23-566a2cc349ac">

**Comment by Jakob37** [comment]
> > Could it be that it hits some max connection time for BioMart (~10 minutes) due to slow write speed and times out?
> 
> Could be
> 
> Alternatively you could download the exons using [schug](https://github.com/Clinical-Genomics/schug) on your local computer, then move it to the server and use it as file_path to do the loading on chanjo2:
> <img alt="image" width="969" src="https://private-user-images.githubusercontent.com/28093618/324350900-3283d5d8-a26c-400a-bb23-566a2cc349ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3Njk3NTAsIm5iZiI6MTcxMzc2OTQ1MCwicGF0aCI6Ii8yODA5MzYxOC8zMjQzNTA5MDAtMzI4M2Q1ZDgtYTI2Yy00MDBhLWJiMjMtNTY2YTJjYzM0OWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA3MDQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwY2IxMDM5NTYwMGFlN2FmY2Q4ZDI3OGQxYTg3MTIxNzBmZGI2YWZlODcwYzY4YTE5ZTliNDEzZDQ0YTNiNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JXZQ4GRHujc5Heecv0qLFmAsdG6jWyL0v7LqE5fXKdA">

OK I see! Nice that you have that functionality. I will give it a go.

**Comment by Jakob37** [comment]
OK, worked nicely to retrieve the exons with schug on my laptop (5 minutes)! But when attempting to load it from file, it was running for some minutes before yielding an error.

Here is the command I ran (inside the Chanjo2 container with the `exons_GRCh38.txt` mounted in)

```
>>> response = requests.post("http://localhost:8000/intervals/load/exons/GRCh38", json={"file_path": "/home/worker/app/exons_GRCh38.txt"})
```

Looking at the response

```
>>> response.text
'Internal Server Error
>>> response.elapsed
datetime.timedelta(seconds=354, microseconds=281551)
>>> response.status_code
500
```

Looking at the logs. Not sure what the issue is. I saw at the `docker stats` that the container was writing some GBs, so looks like something has been happening. Gunicon timeout is set to 1200 seconds, which otherwise would be my first guess.

```
chanjo2               | Traceback (most recent call last):
chanjo2               |   File "/venv/lib/python3.11/site-packages/urllib3/response.py", line 710, in _error_catcher
chanjo2               |     yield
chanjo2               |   File "/venv/lib/python3.11/site-packages/urllib3/response.py", line 1073, in read_chunked
chanjo2               |     self._update_chunk_length()
chanjo2               |   File "/venv/lib/python3.11/site-packages/urllib3/response.py", line 1008, in _update_chunk_length
chanjo2               |     raise InvalidChunkLength(self, line) from None
chanjo2               | urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)
chanjo2               |
chanjo2               | The above exception was the direct cause of the following exception:
chanjo2               |
chanjo2               | Traceback (most recent call last):
chanjo2               |   File "/venv/lib/python3.11/site-packages/requests/models.py", line 816, in generate
chanjo2               |     yield from self.raw.stream(chunk_size, decode_content=True)
chanjo2               |   File "/venv/lib/python3.11/site-packages/urllib3/response.py", line 933, in stream
chanjo2               |     yield from self.read_chunked(amt, decode_content=decode_content)
chanjo2               |   File "/venv/lib/python3.11/site-packages/urllib3/response.py", line 1061, in read_chunked
chanjo2               |     with self._error_catcher():
chanjo2               |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
chanjo2               |     self.gen.throw(typ, value, traceback)
chanjo2               |   File "/venv/lib/python3.11/site-packages/urllib3/response.py", line 727, in _error_catcher
chanjo2               |     raise ProtocolError(f"Connection broken: {e!r}", e) from e
chanjo2               | urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
chanjo2               |
chanjo2               | During handling of the above exception, another exception occurred:
chanjo2               |
chanjo2               | Traceback (most recent call last):
chanjo2               |   File "/home/worker/app/src/chanjo2/endpoints/intervals.py", line 161, in load_exons
chanjo2               |     nr_loaded_exons: int = await update_exons(build=build, session=session)
chanjo2               |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chanjo2               |   File "/home/worker/app/src/chanjo2/meta/handle_load_intervals.py", line 200, in update_exons
chanjo2               |     for line in lines:
chanjo2               |   File "/venv/lib/python3.11/site-packages/requests/models.py", line 865, in iter_lines
chanjo2               |     for chunk in self.iter_content(
chanjo2               |   File "/venv/lib/python3.11/site-packages/requests/utils.py", line 571, in stream_decode_response_unicode
chanjo2               |     for chunk in iterator:
chanjo2               |   File "/venv/lib/python3.11/site-packages/requests/models.py", line 818, in generate
chanjo2               |     raise ChunkedEncodingError(e)
chanjo2               | requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
chanjo2               |
chanjo2               | During handling of the above exception, another exception occurred:
chanjo2               |
chanjo2               | Traceback (most recent call last):
chanjo2               |   File "/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
chanjo2               |     await self.app(scope, receive, sender)
chanjo2               |   File "/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
chanjo2               |     raise e
chanjo2               |   File "/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
chanjo2               |     await self.app(scope, receive, send)
chanjo2               |   File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
chanjo2               |     await route.handle(scope, receive, send)
chanjo2               |   File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
chanjo2               |     await self.app(scope, receive, send)
chanjo2               |   File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
chanjo2               |     response = await func(request)
chanjo2               |                ^^^^^^^^^^^^^^^^^^^
chanjo2               |   File "/venv/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
chanjo2               |     raw_response = await run_endpoint_function(
chanjo2               |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chanjo2               |   File "/venv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
chanjo2               |     return await dependant.call(**values)
chanjo2               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chanjo2               |   File "/home/worker/app/src/chanjo2/endpoints/intervals.py", line 167, in load_exons
chanjo2               |     raise HTTPException(
chanjo2               | fastapi.exceptions.HTTPException
chanjo2               | During handling of the above exception, another exception occurred:
chanjo2               |
chanjo2               | Traceback (most recent call last):
chanjo2               |   File "/venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 429, in run_asgi
chanjo2               |     result = await app(  # type: ignore[func-returns-value]
chanjo2               |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chanjo2               |   File "/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
chanjo2               |     return await self.app(scope, receive, send)
chanjo2               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chanjo2               |   File "/venv/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
chanjo2               |     await super().__call__(scope, receive, send)
chanjo2               |   File "/venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
chanjo2               |     await self.middleware_stack(scope, receive, send)
chanjo2               |   File "/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
chanjo2               |     raise exc
chanjo2               |   File "/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
chanjo2               |     await self.app(scope, receive, _send)
chanjo2               |   File "/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 88, in __call__
chanjo2               |     response = await handler(request, exc)
chanjo2               |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
chanjo2               |   File "/venv/lib/python3.11/site-packages/fastapi/exception_handlers.py", line 15, in http_exception_handler
chanjo2               |     return JSONResponse(
chanjo2               |            ^^^^^^^^^^^^^
chanjo2               |   File "/venv/lib/python3.11/site-packages/starlette/responses.py", line 196, in __init__
chanjo2               |     super().__init__(content, status_code, headers, media_type, background)
chanjo2               |   File "/venv/lib/python3.11/site-packages/starlette/responses.py", line 55, in __init__
chanjo2               |     self.body = self.render(content)
chanjo2               |                 ^^^^^^^^^^^^^^^^^^^^
chanjo2               |   File "/venv/lib/python3.11/site-packages/starlette/responses.py", line 199, in render
chanjo2               |     return json.dumps(
chanjo2               |            ^^^^^^^^^^^
chanjo2               |   File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
chanjo2               |     **kw).encode(obj)
chanjo2               |           ^^^^^^^^^^^
chanjo2               |   File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
chanjo2               |     chunks = self.iterencode(o, _one_shot=True)
chanjo2               |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
chanjo2               |   File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
chanjo2               |     return _iterencode(o, 0)
chanjo2               |            ^^^^^^^^^^^^^^^^^
chanjo2               |   File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
chanjo2               |     raise TypeError(f'Object of type {o.__class__.__name__} '
chanjo2               | TypeError: Object of type ProtocolError is not JSON serializable
```

Any thoughts on how to debug this?

**Comment by northwestwitch** [comment]
Hi, how big is the exons 38 file downloaded from schug? Your database still contains genes and transcripts 38 right?

**Comment by northwestwitch** [comment]
I've tested it locally with the exons file 38 from schug and loads them quite fast (less than a minute)

<img width="1202" alt="image" src="https://github.com/Clinical-Genomics/chanjo2/assets/28093618/a0b5d51d-59d0-4ab2-aa7b-a28ca45e188b">

Haven't tried on dockerised chanjo2 though.

Reading thru your error message it looks like it is still trying to download the exons from Ensembl, which makes me think that perhaps the app doesn't see find the path to the exons in the container?

**Comment by northwestwitch** [comment]
Ahhh, fix the request, so that the file path is passed as a parameter in the URL, like this:

`http://localhost:8000/intervals/load/exons/GRCh38?file_path=/home/worker/app/exons_GRCh38.txt`

**Comment by Jakob37** [comment]
> Ahhh, fix the request, so that the file path is passed as a parameter in the URL, like this:
> 
> `http://localhost:8000/intervals/load/exons/GRCh38?file_path=/home/worker/app/exons_GRCh38.txt`
> 
> I might as well turn it into a GET request, since it's not expecting data, so you have a point in having used a payload, sorry.

Thanks! I'll try it out ..

**Comment by northwestwitch** [comment]
> Yes, it worked 🎉 Thank you for the help! Getting close to having this in place now.

Cool! You're welcome :)
